version: 2

models:
  - name: outclick_cost_int
    description: This is my table
    columns:
      - name: id
        description: The primary key of the table
        tests:
          - unique
          - not_null

  - name: outclick_by_brand_int
    description: This is my table
    columns:
      - name: id
        description: The primary key of the table
        tests:
          - unique
          - not_null


